### ISSUE TITLE
CommClosedError: in <closed TCP>: Stream is closed

### ISSUE THREAD

**Issue by twoertwein** [dask/dask-jobqueue#105]
I tried to create a minimal re-producible example for a different problem I encounter. While doing so, I was able to 're-produce' (it only happens sometimes) a different TCP-related problem.

Code:
```py
import os
import numpy as np
from distributed import Client
from dask_jobqueue import SLURMCluster

def work(large_object):
    return large_object + 1

big_data = np.random.rand(10000, 1000)
graph = {str(i): (work, big_data) for i in range(20)}
targets = list(graph.keys())

workers = 15
kwargs = {'queue': 'cpu_low,cpu_high,gpu_low', 'resource_spec': '',
          'diagnostics_port': None,
          'cores': 8, 'memory': '15G',
          'walltime': '70:00:00', 'interface': 'em2'}

for i in range(10):
    print(i)
    with SLURMCluster(**kwargs) as cluster:
        cluster.scale(workers)
        with Client(cluster, local_directory=os.getcwd()) as client:
            big_datas = client.get(graph, targets)
```

Output:
```
0
/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/worker.py:820: UserWarning: Large object of size 80.00 MB detected in task graph: 
  (array([[0.72155014, 0.38726907, 0.92209933, ...,  ... 0.9996717 ]]),)
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s))
1
2
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
3
4
5
6
7
8
9
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

dask-worker.err 
```
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 259, in <module>
    go()
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 255, in go
    main()
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 206, in main
    host = get_ip_interface(interface)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/utils.py", line 160, in get_ip_interface
    for info in psutil.net_if_addrs()[ifname]:
KeyError: 'em2'
distributed.worker - INFO -       Start worker at:   tcp:distributed.worker - INFO -         Registered to:     tcp://10.1.188.1:37110
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 259, in <module>
    go()
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 255, in go
    main()
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 206, in main
    host = get_ip_interface(interface)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/utils.py", line 160, in get_ip_interface
    for info in psutil.net_if_addrs()[ifname]:
KeyError: 'em2'
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:37966
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:35165
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:33751
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:43891
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:40034'
slurmstepd: error: *** JOB 5561 ON compute-0-18 CANCELLED AT 2018-07-25T20:29:19 ***
slurmstepd: error: *** JOB 5559 ON compute-0-18 CANCELLED AT 2018-07-25T20:29:19 ***
slurmstepd: error: *** JOB 5560 ON compute-0-18 CANCELLED AT 2018-07-25T20:29:19 ***
slurmstepd: error: *** JOB 5558 ON compute-0-18 CANCELLED AT 2018-07-25T20:29:19 ***
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:44738'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:46345'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:33371'
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - End worker
```

Versions:
ipython: 6.4.0
dask: 0.18.2
dask_jobqueue: 0.3.0

**Comment by mrocklin** [comment]
My guess is that the interface you're using, em2, is not avaiable on some
of your workers

**Comment by twoertwein** [comment]
oh thanks, that might be the case. I thought 'interface' would only specify which interface to use on the cluster head (not on the workers). Is that incorrect?

**Comment by twoertwein** [comment]
I removed the 'interface' argument, the error still occurs:

Output:
```
0
/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/worker.py:820: UserWarning: Large object of size 80.00 MB detected in task graph: 
  (array([[0.4442631 , 0.62320326, 0.05311121, ...,  ... 0.19558944]]),)
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s))
1
2
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
3
4
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/core.py", line 432, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
5
6
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/twoertwe/miniconda3/envs/panama/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
7
8
9
```

dask-worker.err
```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.188.253:36131'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.188.253:37310'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.188.253:44237'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.188.253:42312'
distributed.worker - INFO -       Start worker at:   tcp://10.1.188.248:34583
distributed.worker - INFO -          Listening to:   tcp://10.1.188.248:34583
distributed.worker - INFO -              nanny at:         10.1.188.248:43423
distributed.worker - INFO -              bokeh at:          10.1.188.248:8789
distributed.worker - INFO - Waiting to connect to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   15.00 GB
distributed.worker - INFO -       Local Directory: /home/twoertwe/git/python_tools/dask-worker-space/worker-kk025weh
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
 10.1.188.253:42312
distributed.worker - INFO -              bokeh at:         10.1.188.253:39719
distributed.worker - INFO - Waiting to connect to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   15.00 GB
distributed.worker - INFO -       Local Directory: /home/twoertwe/git/python_tools/dask-worker-space/worker-th30p0im
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:   tcp://10.1.188.253:35669
distributed.worker - INFO -          Listening to:   tcp://10.1.188.253:35669
distributed.worker - INFO -              nanny at:         10.1.188.253:37310
distributed.worker - INFO -              bokeh at:         10.1.188.253:37778
distributed.worker - INFO - Waiting to connect to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   15.00 GB
distributed.worker - INFO -       Local Directory: /home/twoertwe/git/python_tools/dask-worker-space/worker-7w8_unta
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:   tcp://10.1.188.253:46509
distributed.worker - INFO -          Listening to:   tcp://10.1.188.253:46509
distributed.worker - INFO -              nanny at:         10.1.188.253:44237
distributed.worker - INFO -              bokeh at:         10.1.188.253:40377
distributed.worker - INFO - Waiting to connect to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   15.00 GB
distributed.worker - INFO -       Local Directory: /home/twoertwe/git/python_tools/dask-worker-space/worker-ubzhiom0
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:  tcp://128.2.204.188:39860
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:36404
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:43098
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:35669
distributed.worker - INFO - Stopping worker at tcp://10.1.188.253:46509
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
slurmstepd: error: *** JOB 5711 ON compute-0-18 CANCELLED AT 2018-07-25T21:03:27 ***
distributed.worker - INFO - -------------------------------------------------
slurmstepd: error: *** JOB 5710 ON compute-0-18 CANCELLED AT 2018-07-25T21:03:27 ***
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
slurmstepd: error: *** JOB 5709 ON compute-0-18 CANCELLED AT 2018-07-25T21:03:27 ***
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:42312'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:36131'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:37310'
slurmstepd: error: *** JOB 5708 ON compute-0-18 CANCELLED AT 2018-07-25T21:03:27 ***
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.188.253:44237'
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker

```

**Comment by mrocklin** [comment]
It looks like your workers can't talk to each other or to the scheduler.
My guess is that they're listening different networks.  Unfortunately I'm
not able to help out on this much.  I recommend asking someone familiar
with your network to help.

**Comment by twoertwein** [comment]
If that is the case, shouldn't it always fail? I'm quite sure they are able to talk to each other - they are all in the same subnet (the cluster head has a second interface, which is why I originally specified 'em2' for it).

**Comment by twoertwein** [comment]
ok, thanks. I hope I find what is going wrong

**Comment by mrocklin** [comment]
Good luck!
