### ISSUE TITLE
distributed.utils - ERROR - Worker already exists

### ISSUE THREAD

**Issue by Sutyke** [dask/dask-jobqueue#240]
I would like to ask if there is any solution to the issue below. at the moment dask can not be used for scaling tpot as when running after while there is cumming error message and dask freeze. 

For more info please  see the link documentation below: 
https://examples.dask.org/machine-learning/tpot.html

In the section "Using Dask" when tp.fit(X_train, y_train) I'm getting the same error as below:

distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:46060
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/distributed/utils.py", line 648, in log_errors
    yield
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/distributed/scheduler.py", line 1278, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:46060
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:46060
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/distributed/scheduler.py", line 1278, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:46060

Could you please help if there is any possibility to run dask with tpot at the moment?

Thanks for advice

**Comment by guillaumeeb** [comment]
Are you using jobqueue, or Local cluster? This seems to me more a dask or distributed question, not particularly jobqueue related?

**Comment by Sutyke** [comment]
Hi,

I was using jobqueu but it happens also on local closure. Can you move it
to distributed ?

**Comment by guillaumeeb** [comment]
Hm, I don't think I can. @mrocklin or maybe @TomAugspurger because this seems related to dask-ml also, can you move this issue in another repo?
