### ISSUE TITLE
HTCondor cluster cannot scale up

### ISSUE THREAD

**Issue by simone-codeluppi** [dask/dask-jobqueue#350]
Hi
I finally had the chance to test dask-jobqueue on our HTCondor cluster. Thanks @matyasselmeci for creating the functionality!

As reported in the API guide [HTCondor_API](https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.HTCondorCluster.html#) 
i run:

```python
from dask_jobqueue.htcondor import HTCondorCluster
cluster = HTCondorCluster(cores=24, memory="4GB", disk="4GB")
```

When I scale up to  10 jobs 

```python
cluster.scale(jobs=10)  # ask for 10 jobs
```

 I get the following error :  

```python
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fcaf8bb2780>>, <Task finished coro=<
SpecCluster._correct_state_internal() done, defined at /fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/distributed/deploy/spec.py:284> exception=RuntimeError('Command exited wi
th non-zero exit code.\nExit code: 1\nCommand:\ncondor_submit -queue 1 -file /tmp/tmpvytzt0ez.sh\nstdout:\n\nstderr:\nUsage: condor_submit [options] [<attrib>=<value>] [- | <submit-file>]\n    [options] a
re\n\t-terse  \t\tDisplay terse output, jobid ranges only\n\t-verbose\t\tDisplay verbose output, jobid and full job ClassAd\n\t-debug  \t\tDisplay debugging output\n\t-append <line>\t\tadd line to submit 
file before processing\n\t              \t\t(overrides submit file; multiple -a lines ok)\n\t-queue <queue-opts>\tappend Queue statement to submit file before processing\n\t                   \t(submit fi
le must not already have a Queue statement)\n\t-batch-name <name>\tappend a line to submit file that sets the batch name\n\t-disable\t\tdisable file permission checks\n\t-dry-run <filename>\tprocess submi
t file and write ClassAd attributes to <filename>\n\t        \t\tbut do not actually submit the job(s) to the SCHEDD\n\t-maxjobs <maxjobs>\tDo not submit if number of jobs would exceed <maxjobs>.\n\t-sing
le-cluster\t\tDo not submit if more than one ClusterId is needed.\n\t-unused\t\t\ttoggles unused or unexpanded macro warnings\n\t       \t\t\t(overrides config file; multiple -u flags ok)\n\t-dump <filena
me>\tWrite job ClassAds to <filename> instead of\n\t                \tsubmitting to a schedd.\n\t-interactive\t\tsubmit an interactive session job\n\t-name <name>\t\tsubmit to the specified schedd\n\t-rem
ote <name>\t\tsubmit to the specified remote schedd\n\t              \t\t(implies -spool)\n\t-addr <ip:port>\t\tsubmit to schedd at given "sinful string"\n\t-spool\t\t\tspool all files to the schedd\n\t-password <password>\tspecify password to MyProxy server\n\t-pool <host>\t\tUse host as the central manager to query\n\t-stm <method>\t\tHow to move a sandbox into HTCondor\n\t             \t\t<methods> is one of: stm_use_schedd_only\n\t             \t\t                     stm_use_transferd\n\t<attrib>=<value>\tSet <attrib>=<value> before reading the submit file.\n\n    If <submit-file> is omitted or is -, input is read from stdin.\n    Use of - implies verbose output unless -terse is specified\n\n')>)
Traceback (most recent call last):
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/distributed/deploy/spec.py", line 317, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/distributed/deploy/spec.py", line 41, in _
    await self.start()
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 285, in start
    out = await self._submit_job(fn)
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 268, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/fish/simone_processing/anaconda3/envs/dask_htc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 368, in _call
    "stderr:\n{}\n".format(proc.returncode, cmd_str, out, err)
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
condor_submit -queue 1 -file /tmp/tmpvytzt0ez.sh
stdout:
stderr:
Usage: condor_submit [options] [<attrib>=<value>] [- | <submit-file>]
    [options] are
        -terse                  Display terse output, jobid ranges only
        -verbose                Display verbose output, jobid and full job ClassAd
        -debug                  Display debugging output
        -append <line>          add line to submit file before processing
                                (overrides submit file; multiple -a lines ok)
        -queue <queue-opts>     append Queue statement to submit file before processing
                                (submit file must not already have a Queue statement)
        -batch-name <name>      append a line to submit file that sets the batch name
        -disable                disable file permission checks
        -dry-run <filename>     process submit file and write ClassAd attributes to <filename>
                                but do not actually submit the job(s) to the SCHEDD
        -maxjobs <maxjobs>      Do not submit if number of jobs would exceed <maxjobs>.
        -single-cluster         Do not submit if more than one ClusterId is needed.
        -unused                 toggles unused or unexpanded macro warnings
                                (overrides config file; multiple -u flags ok)
        -dump <filename>        Write job ClassAds to <filename> instead of
                                submitting to a schedd.
        -interactive            submit an interactive session job
        -name <name>            submit to the specified schedd
        -remote <name>          submit to the specified remote schedd
                                (implies -spool)
        -addr <ip:port>         submit to schedd at given "sinful string"
        -spool                  spool all files to the schedd
        -password <password>    specify password to MyProxy server
        -pool <host>            Use host as the central manager to query
        -stm <method>           How to move a sandbox into HTCondor
                                <methods> is one of: stm_use_schedd_only
                                                     stm_use_transferd
        <attrib>=<value>        Set <attrib>=<value> before reading the submit file.

    If <submit-file> is omitted or is -, input is read from stdin.
    Use of - implies verbose output unless -terse is specified
```

Any idea? Has something to do with the specific condor setup of the cluster I am using?

Thanks for the help.

**Comment by matyasselmeci** [comment]
Hi Simone,
Looks like you're running an older version of HTCondor that does not support the -file argument. #319 will fix this but there's other changes in that PR that are still being discussed. I'll ask if we can merge the -file argument fix now and discuss the other features later.

**Comment by simone-codeluppi** [comment]
Hi
great! thanks a lot!
