### ISSUE TITLE
Worker startup is very slow and times out (sometimes)

### ISSUE THREAD

**Issue by fabiansvara** [dask/dask-jobqueue#448]
I've been running into a problem on a SLURM cluster, where if I do `wait_for_workers` after `cluster.scale` the requested number of workers is not reached because workers die due to a timeout error. I was able to work around that by setting `death-timeout: 240` in `jobqueue.yaml`; `allowed-failures: 12` and `worker-ttl: "180s"` in `distributed.yaml`. I am not sure which one of these parameters exactly made the difference, I increased all of them together several times until the problem seemed to be gone for good.

The timeout error I saw in the workers was this:

```
Traceback (most recent call last):
  File "/my/conda/env/lib/python3.8/site-packages/distributed/core.py", line 226, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/my/conda/env/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/my/conda/env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/my/conda/env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/my/conda/env/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 452, in <module>
    go()
  File "/my/conda/env/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 448, in go
    main()
  File "/my/conda/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/my/conda/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/my/conda/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/my/conda/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/my/conda/env/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 434, in main
    loop.run_sync(run)
  File "/my/conda/env/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/my/conda/env/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 428, in run
    await asyncio.gather(*nannies)
  File "/my/conda/env/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/my/conda/env/lib/python3.8/site-packages/distributed/core.py", line 230, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds

[...]

Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/my/conda/env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/my/conda/env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/my/conda/env/lib/python3.8/site-packages/distributed/process.py", line 234, in _watch_process
    assert exitcode is not None
AssertionError
```

Even with the drastically increased timeouts, the worker startup behavior is still quite fishy, as demonstrated by the following testing code:

```python
from dask_jobqueue import SLURMCluster
from dask.distributed import Client
import time
import os
import platform

def _worker(worker_id):
    print(f'{worker_id=} starting (pid={os.getpid()} on {platform.node()}).')
    time.sleep(10)
    print(f'{worker_id=} done.')

def dask_map(cores, nodes, processes):
    cluster = SLURMCluster(
        cores=cores,
        processes=processes,
        memory='370GB',
        walltime='24:00:00',
        queue='my.queue',
        shebang='#!/bin/bash -l',
        local_directory='/my/local/dir',
        env_extra=[
            'module load anaconda',
            'conda init bash',
            'conda activate /my/conda/env', ])
    cluster.scale(nodes * processes)
    client = Client(cluster)
    while True:
        active_workers = len(client.scheduler_info()["workers"])
        print(f'{active_workers}, ', end='', flush=True)
        if active_workers >= nodes * processes:
            print('')
            break
        time.sleep(5)
    f = client.map(_worker, list(range(nodes * processes)))
    [xx.result() for xx in f]
    cluster.scale(n=0, jobs=0)
    cluster.close()

def nanny_timeout():
    for i in range(0, 6):
        print(f'24 nodes; iteration {i}.')
        dask_map(cores=40, nodes=24, processes=40)

if __name__ == '__main__':
    nanny_timeout()
```

... this prints the number of workers as they are spinning up:

```
24 workers; iteration 0.
0, 0, 0, 0, 0, 0, 40, 85, 253, 679, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 939, 949, 960,
24 workers; iteration 1.
0, 0, 0, 0, 0, 35, 86, 207, 389, 829, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 939, 945, 960,
24 workers; iteration 2.
0, 0, 0, 0, 0, 6, 81, 151, 199, 432, 749, 873, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 937, 938, 960,
24 workers; iteration 3.
0, 0, 0, 0, 0, 0, 85, 119, 242, 512, 760, 851, 904, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 938, 952, 960,
24 workers; iteration 4.
0, 0, 0, 0, 0, 28, 97, 190, 342, 750, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 940, 951, 960,
24 workers; iteration 5.
0, 0, 0, 0, 0, 0, 93, 236, 614, 841, 872, 933, 936, 936, 936, 936, 936, 936, 936, 936, 936, 936, 937, 939, 941, 960,
```

For one, it takes extremely long for the workers to start up, with nothing happening for ~30 s. The other odd thing is that in all cases, it hangs for a long time at exactly 936 workers (exactly the number of nodes less than the expected total number of workers).

I am observing the status of the SLURM jobs in `squeue` while testing, and I can see that all of the SLURM jobs are up and running (`R` state) within seconds, so this is totally unrelated to SLURM's scheduling.

Anyway, the high timeouts work as a workaround for me, but my worry is that this may not fix the issue always and it will crop up randomly again. Also, the behavior seems so fishy to me that I wonder if there isn't something fundamentally wrong here, either on my side or with dask.

**Environment**:

- Dask version: 2.18.1
- Python version: 3.8.3
- Operating System: Linux  3.10.0
- Install method (conda, pip, source): conda

**Comment by fabiansvara** [comment]
Ok - I can already answer my own question ;)

The problem here was that `local_directory` was set to the cluster's shared scratch space, which is on GPFS, making it too slow apparently.

**Comment by mrocklin** [comment]
You may want to read through https://docs.dask.org/en/latest/setup/hpc.html for
some best practices on HPC architectures

**Comment by mrocklin** [comment]
Oh, and thanks for raising an issue on github and following up.  Hopefully
your experience helps others in future web searches.
