### ISSUE TITLE
Can't get results from HTCondorCluster

### ISSUE THREAD

**Issue by maxgalli** [dask/dask-jobqueue#475]
Dear developers,

I'm experiencing some problems submitting jobs with ```HTCondorCluster```.

This is the simple example I'm trying to run:
```python
from dask.distributed import Client, progress
from dask_jobqueue.htcondor import HTCondorCluster

def dummy_function(num):
    return num

def main():
    cluster = HTCondorCluster(cores=1, memory='1GB', disk='1GB')
    cluster.scale(jobs=3)
    client = Client(cluster)
    futures = client.map(dummy_function, range(3))
    progress(futures)
    res = client.gather(futures)
    print('\n', res)

if __name__ == '__main__':
    main()
```
I would expect to see the progress bar completed and then a list ```[0, 1, 2]``` printed.
What happens is that the jobs **seem** to run: if I run ```condor_q``` I initially see 3 jobs in idle, then they start running until all of them are done. But where I should see the bar at 100% and the list printed I only see the bar at 0% with the time running.
If I do the same interactively with IPython I see that status of the futures is ```pending``` even after all the jobs finished running.

Am I doing something wrong?

**Environment**:

- Dask version: 2.20.0
- Python version: 3.7.8
- Operating System: Centos7
- Install method (conda, pip, source): conda

As a side note, the same example run on a different cluster with ```SLURMCluster``` instead of ```HTCondorCluster``` works as expected.

Thank you,

Massimiliano

**Comment by oshadura** [comment]
Hey @maxgalli, I would suggest you to look into https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.HTCondorCluster.html constructor and tune arguments `extra`, `job_extra` and even `scheduler_options` according your job description file `x.sub` (or to try to at least to get logs and see what could be missing from created job ClassAd).

**Comment by maxgalli** [comment]
Thanks @oshadura, I tried to run the following:
```python
from distributed import Client
from dask_jobqueue import HTCondorCluster

def main():
    with HTCondorCluster(
            cores=1,
            memory='100MB',
            disk='100MB',
            death_timeout = '600',
            job_extra={
                'log': 'dask_job_output.log',
                'output': 'dask_job_output.out',
                'error': 'dask_job_output.err',
                'should_transfer_files': 'Yes',
                'when_to_transfer_output': 'ON_EXIT'
                }
            ) as cluster:
        with Client(cluster) as client:
            cluster.scale(2)
            future = client.submit(lambda x: x + 1, 10)
            print(future.result())

if __name__ == '__main__':
    main()
```
and ```dask_job_output.err``` says the following:
```
distributed.nanny - INFO -         Start Nanny at: 'tcp://188.184.192.124:38706'
distributed.worker - INFO -       Start worker at: tcp://188.184.192.124:36889
distributed.worker - INFO -          Listening to: tcp://188.184.192.124:36889
distributed.worker - INFO -          dashboard at:      188.184.192.124:42621
distributed.worker - INFO - Waiting to connect to: tcp://137.138.121.181:45167
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  100.00 MB
distributed.worker - INFO -       Local Directory: /pool/condor/dir_1974/dask-worker-space/dask-worker-space/worker-wzmsj6h6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to: tcp://137.138.121.181:45167
distributed.worker - INFO - Waiting to connect to: tcp://137.138.121.181:45167
(...)
distributed.worker - INFO - Waiting to connect to: tcp://137.138.121.181:45167
distributed.worker - INFO - Waiting to connect to: tcp://137.138.121.181:45167
distributed.nanny - INFO - Closing Nanny at 'tcp://188.184.192.124:38706'
distributed.worker - INFO - Stopping worker at tcp://188.184.192.124:36889
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/core.py", line 280, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 450, in <module>
    go()
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 446, in go
    main()
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 432, in main
    loop.run_sync(run)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 426, in run
    await asyncio.gather(*nannies)
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/afs/cern.ch/work/g/gallim/anaconda3/envs/dask-pyroot-tutorial/lib/python3.7/site-packages/distributed/core.py", line 286, in _
    type(self).__name__, timeout
concurrent.futures._base.TimeoutError: Nanny failed to start in 600 seconds
```

I took a look and it seems similar to this thread (https://github.com/dask/dask-jobqueue/issues/391).

Is there anything in particular I should try to do differently and/or ask to the cluster IT?

Thanks

**Comment by oshadura** [comment]
@maxgalli it looks like a problem with network, you will need to ask somebody from CERN IT to open ports...

**Comment by maxgalli** [comment]
It was a setup problem with our batch queuing system, solved here https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF1699933. 
I'm thus going to close this.

**Comment by guillaumeeb** [comment]
Hi @maxgalli, I'm glad you find the fix to your problem.

I've got to ask, I'm really curious about what you are doing at CERN with Dask! Did it finally help you to do some science?

**Comment by maxgalli** [comment]
Hi @guillaumeeb, sorry for the late reply. 
I'm working on rewriting an analysis framework for Higgs to two gamma analysis. 
Since it will have to run on (at least) two clusters using HTCondor and SLURM, Dask (+ joblib) looks like the perfect solution to have a common API for both of them. But right now I'm still at an early stage, so I don't have much more information :)

On a wider and more general scenario, they mentioned the idea of providing workload distribution with Dask "as a service" (you can see it in the ticket I attached above), so I guess it will be used more in the future.

**Comment by guillaumeeb** [comment]
Thanks for the explanation, I hope Dask will answer your need and others at CERN!
