### ISSUE TITLE
Lost connection to scheduler process on login node (HTCondor)

### ISSUE THREAD

**Issue by simone-codeluppi** [dask/dask-jobqueue#493]
**What happened**:
 
Hi 

I am processing 800-1000 3D microscopy images using `dask/dask-jobqueue` on an `htcondor` managed cluster. Each 3D image is processed in parallel (embarrassingly parallel application using mapping functions and gathering futures). Each image is processed in a separated `job` managed by a `worker`. The min and max number of `jobs/workers` is regulated by adaptive scaling (min, max). The expected processing time of a task is quite long (~1hr)

The processing time of each task increases over time and usually the last tasks take hrs (~5-10hrs) to be completed or the processing stalls. The tasks that are run for longer time or stall are random (different images can be processed last). This is similar to what is reported here: [#2835](https://github.com/dask/distributed/issues/2835) but having `ctoolz` didn't solve the issue

The `task log` for this long running tasks shows that the task status cycle between `waiting --> running` to `processing-->released` many many times. The processing resources aren't an issue. In some cases an error related to connection to the scheduler is printed (see below) so it seems that the worker (still up in the dashboard) looses the connection to the scheduler (temporarily or forever if the process stall). 

Interestingly enough this issue is less frequent if I build a graph and use `client.get` instead of using the `future api with client.gather`

```python

distributed.utils - ERROR - Timed out during handshake while connecting to tcp://192.168.0.2:35688 after 10 s                                      [112/221]
Traceback (most recent call last):
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/home/simone/mini/envs/test_d/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/utils.py", line 655, in log_errors
    yield
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/scheduler.py", line 3515, in retire_workers
    await self.replicate(
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/scheduler.py", line 3281, in replicate
    results = await asyncio.gather(
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/utils_comm.py", line 385, in retry_operation
    return await retry(
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/core.py", line 880, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/core.py", line 1031, in connect
    comm = await connect(
  File "/home/simone/mini/envs/test_d/lib/python3.8/site-packages/distributed/comm/core.py", line 324, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to tcp://192.168.0.2:35688 after 10 s
```

It is difficult for me to provide a working minimal example because the issue happens only when the processing has been going on for quite a while (hrs) and not always after the same amount of time.

Any hint to what to look for in order to run a proper debugging will be helpful

Thanks.

**Anything else we need to know?**:

**Environment**:

- Dask version: 
dask                      2.14.0                     py_0    conda-forge
dask-core                 2.14.0                     py_0    conda-forge
dask-jobqueue             0.7.2                    pypi_0    pypi

or

dask                      2021.3.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.3.1           pyhd8ed1ab_0    conda-forge
dask-jobqueue             0.7.2                    pypi_0    pypi

- Python version: 3.8.5
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by jacobtomlinson** [comment]
The problem you mention with the scheduler losing connection may be an environmental issue in your HPC, but other than that I think this issue is more around long running tasks in distributed rather than deployment issues in dask-jobqueue.

I'm going to move it to another repo to get more visibility on it.

I think if you could share the logs from the scheduler and workers along with the task log that may help.
