### ISSUE TITLE
Doc build is failing

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#512]
Started failing two weeks ago: https://readthedocs.org/projects/dask-jobqueue/builds/14170262/

Very likely a Sphinx change ...

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/conda/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 257, in __init__
    self.config.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/checkouts/latest/docs/source/conf.py", line 210, in setup
    app.add_stylesheet("basic.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/checkouts/latest/docs/source/conf.py", line 210, in setup
    app.add_stylesheet("basic.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

**Comment by ocaisa** [comment]
Yeah, that is deprecated for a while:
https://github.com/sphinx-doc/sphinx/issues/7747#issuecomment-636023612
