### ISSUE TITLE
SLURM workers not getting queued

### ISSUE THREAD

**Issue by krpandit** [dask/dask-jobqueue#564]
**What happened**:
workers are not submitted to SLURM

**What you expected to happen**:
workers get queued up SLURM

**Minimal Complete Verifiable Example**:

```python
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster()
cluster.scale(2)
```
No jobs are queued in SLURM
Check running python command from `cluster.jobscript`
```
python -m distributed.cli.dask_worker tcp://XX.X.XXX.XX:XXXX

Traceback (most recent call last):
  File "/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/site-packages/distributed/cli/dask_worker.py", line 495, in <module>
    go()  # pragma: no cover
  File "/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/site-packages/distributed/cli/dask_worker.py", line 490, in go
    check_python_3()
  File "/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/site-packages/distributed/cli/utils.py", line 38, in check_python_3
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/gpfs/commons/home/kpandit/mambaforge/envs/pyseq_image/lib/python3.9/site-packages/click/__init__.py)
```

**Anything else we need to know?**:
revert click back to 8.0.2 (py39hf3d152e_0, conda-forge) fixed the issue

**Environment**:
dask-jobqueue             0.7.4              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forg

- Dask version: 2022.3.0           pyhd8ed1ab_1    conda-forge
- Python version: 3.9.13          h2660328_0_cpython    conda-forge
- Operating System: unix
- Install method (conda, pip, source):

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by guillaumeeb** [comment]
Thanks @willirath for the quick answer!

@krpandit I'm going to close this issue as this had been fixed upstream in distributed.

Feel free to comment or reopen if you think this doesnot solve your problem.
