### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by mens-artis** [dask/dask-jobqueue#614]
**I have a peristent issue when running dask jobqueue from smac3 with a SlurmCluster() which builds on jobqueue**:
```
import datetime
import numpy as np
#import torch
from ConfigSpace import (
    Categorical,
    Configuration,
    ConfigurationSpace,
    Float,
    Integer,
)
from smac import MultiFidelityFacade as MFFacade
from smac import Scenario
from smac.facade import AbstractFacade
from smac.intensifier.hyperband import Hyperband
from smac.intensifier.successive_halving import SuccessiveHalving
from tqdm import tqdm

import dask.config
import dask.distributed
from dask.distributed import Client
from dask_jobqueue import SLURMCluster


class LRN:
    @property
    def configspace(self) -> ConfigurationSpace:
        cs = ConfigurationSpace()
        rank = Integer("r", (2, 8), log=True, default=2)
        cs.add_hyperparameters([r])

        return cs


    def gpu_checks(self, *args, seed: int = 0, budget: int = 25):
        # setting device on GPU if available, else CPU
        print("MAKE A WISH")
        return seed * 1.0


from smac import RandomFacade

if __name__ == "__main__":
    lorin = LRN()
    if True:

        scenario = Scenario(
            lorin.configspace,
            walltime_limit=120,
            n_trials=50,
            min_budget=1,
            max_budget=64  #,
            #deterministic=True,
        )

        # Create cluster
        n_workers = 1
        cluster = SLURMCluster(
            queue="partitionname",
            cores=4,  # n_cpus
            memory="2000000000",
            walltime="00:02:00",
            processes=1, 
            death_timeout=3600,
            log_directory="logs/31/"  #,
            #job_extra_directives=["--gres=gpu:2"]
        )
        cluster.scale(jobs=n_workers)
        print(cluster.job_script())
        # worker_extra_args=["--gres gpu=2"],

        print("0. the time is {}".format(datetime.datetime.now()))
        client = Client(
            address=cluster,
        )
        print("client: {}".format(client))
        # initial_design = MFFacade.get_initial_design(scenario, n_configs=5)
        initial_design = RandomFacade.get_initial_design(scenario)  #, n_configs=5)
        print("initial design: {}".format(initial_design))
        #intensifier = intensifier_object(scenario, incumbent_selection="highest_budget")
        intensifier = RandomFacade.get_intensifier(scenario, max_config_calls=1, max_incumbents=1)
        print("intensifier: {}".format(intensifier))
        smac = RandomFacade(
            scenario=scenario,
            target_function=lorin.gpu_checks,  # pfn.train_and_eval,
            #*,
            #model=None, acquisition_function=None, acquisition_maximizer=None,
            initial_design=initial_design,
            #random_design=None,
            intensifier=intensifier,
            #multi_objective_algorithm=None, runhistory_encoder=None, config_selector=None, logging_level=None, callbacks=[],
            overwrite=True,
            dask_client=client
         )
        print("1. the time is {}".format(datetime.datetime.now()))
        #incumbent = smac.optimize()
        print("smac: {}".format(smac))
        smac.optimize()
        # print(dask.config.config)
        #print()
        print("2. the time is {}".format(datetime.datetime.now()))

```

**Anything else we need to know?**:

**Environment**:

- Dask version:
```
Package            Version
------------------ --------
click              8.1.7
cloudpickle        2.2.1
ConfigSpace        0.7.1
dask               2023.9.1
dask-jobqueue      0.8.2
distributed        2023.9.1
emcee              3.1.4
fsspec             2023.9.0
importlib-metadata 6.8.0
Jinja2             3.1.2
joblib             1.3.2
locket             1.0.0
MarkupSafe         2.1.3
more-itertools     10.1.0
msgpack            1.0.5
numpy              1.25.2
packaging          23.1
partd              1.4.0
pip                22.2.1
psutil             5.9.5
pynisher           1.0.9
pyparsing          3.1.1
pyrfr              0.9.0
PyYAML             6.0.1
regex              2023.8.8
scikit-learn       1.3.0
scipy              1.11.2
setuptools         63.2.0
smac               2.0.2
sortedcontainers   2.4.0
tblib              2.0.0
threadpoolctl      3.2.0
toolz              0.12.0
tornado            6.3.3
tqdm               4.66.1
typing_extensions  4.7.1
urllib3            2.0.4
zict               3.0.0
zipp               3.16.2
```
- Python version: 3.10.6 (Python had to match between scheduler and worker to avoid a Warning on this)
- Operating System:  Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-76-generic x86_64)
- Install method (conda, pip, source): python 3.6.10 from source

I print the sbatch script:

```
#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -e logs/31//dask-worker-%J.err
#SBATCH -o logs/31//dask-worker-%J.out
#SBATCH -p partitionname
#SBATCH -n 1
#SBATCH --cpus-per-task=4
#SBATCH --mem=2G
#SBATCH -t 00:02:00

/home/username/.python3.10.6/bin/python3.10 -m distributed.cli.dask_worker tcp://....166.214:36441 --nthreads 4 --memory-limit 1.86GiB --name dummy-name --nanny --death-timeout 120
```
 and run it and it breathes out:

```$ cat logs/31/dask-worker-9276970.err
cpu-bind=MASK - dlcgpu16, task  0  0 [2812916]: mask 0x300000003000 set
2023-09-14 13:20:10,029 - distributed.nanny - INFO - Closing Nanny at 'tcp://....166.176:40251'. Reason: failure-to-start-<class 'OSError'>
2023-09-14 13:20:10,030 - distributed.dask_worker - INFO - End worker
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/utils.py", line 1920, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/home/username/.python3.10.6/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/comm/tcp.py", line 503, in connect
    convert_stream_closed_error(self, e)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/comm/tcp.py", line 141, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x7f1bb6ce5f60>: ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/core.py", line 616, in start
    await wait_for(self.start_unsafe(), timeout=timeout)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/utils.py", line 1920, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/home/username/.python3.10.6/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/nanny.py", line 353, in start_unsafe
    comm = await self.rpc.connect(saddr)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/core.py", line 1626, in connect
    return connect_attempt.result()
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/core.py", line 1516, in _connect
    comm = await connect(
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/comm/core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://....166.214:36441 after 30 s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/.python3.10.6/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.python3.10.6/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/cli/dask_worker.py", line 544, in <module>
    main()  # pragma: no cover
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/cli/dask_worker.py", line 450, in main
    asyncio_run(run(), loop_factory=get_loop_factory())
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/compatibility.py", line 236, in asyncio_run
    return loop.run_until_complete(main)
  File "/home/username/.python3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/cli/dask_worker.py", line 447, in run
    [task.result() for task in done]
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/cli/dask_worker.py", line 447, in <listcomp>
    [task.result() for task in done]
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/cli/dask_worker.py", line 420, in wait_for_nannies_to_finish
    await asyncio.gather(*nannies)
  File "/home/username/.python3.10.6/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/username/.python3.10.6/lib/python3.10/site-packages/distributed/core.py", line 624, in start
    raise RuntimeError(f"{type(self).__name__} failed to start.") from exc
RuntimeError: Nanny failed to start.
```
I had inserted the following code at the top of submit_trial(), to avoid a timeout from the scheduler (which works and seems unrelated):
```
import asyncio
```
and
```
try:
    self._client.wait_for_workers(n_workers=1, timeout=1200)
except asyncio.exceptions.TimeoutError as error:
    logger.debug(f"No worker could be scheduled in time after {self._worker_timeout}s on the cluster. "
                  "Try increasing `worker_timeout`.")
    raise error
```
with
```$ nano /home/username/venv/lib/python3.10/site-packages/smac/runner/dask_runner.py```

Is this something a non admin user can fix?

**Comment by mens-artis** [comment]
I put some prints in tcp.py. It basically means tells there is no writeable buffer for the stream (line 316).

```message in tcp.py: {'compression': None, 'python': (3, 10, 6), 'pickle-protocol': 5}
[b':\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00', b'\x83\xabcompression\xc0\xa6python\x93\x03\n\x06\xafpickle-protocol\x05']
small
memoryview:  <memory at 0x7f79646b87c0>
size:  66
dozing off ...
returning  66
message in tcp.py: {'compression': None, 'python': (3, 10, 6), 'pickle-protocol': 5}
[b':\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00', b'\x83\xabcompression\xc0\xa6python\x93\x03\n\x06\xafpickle-protocol\x05']
small
memoryview:  <memory at 0x7f79646b8a00>
```

**Comment by mens-artis** [comment]
It seems that the program just ends with an error, like, one end of the TCP connection continueing after the job is finished. This does cause a problem, notably that my GPUinfo cannot be run but it seems to be a side effect of the discoonection. Or, even a different problem. So I guess I will delete it here. I don't have time to study it further and taking a different approach.

**Comment by guillaumeeb** [comment]
Hi @mens-artis,

I'm not sure about the context here, you are talking about `SMAC3` or `GPUinfo` which I don't know about.

Anyway, yes, there are sometimes Error messages when shutting down a Dask cluster, but as you've noticed, this does not cause a problem for your computation.
