### ISSUE TITLE
Test failure: Exception: get_data() got an unexpected keyword argument 'max_connections'

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#98]
I'm getting a few test failures on master when running the pbs tests in the docker environment.

```Python-traceback
/opt/anaconda/lib/python3.6/site-packages/distributed/core.py:448: Exception
------------------------------ Captured log setup ------------------------------
selector_events.py          65 DEBUG    Using selector: EpollSelector
selector_events.py          65 DEBUG    Using selector: EpollSelector
----------------------------- Captured stderr call -----------------------------
distributed.core - ERROR - get_data() got an unexpected keyword argument 'max_connections'
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/core.py", line 320, in handle_comm
    result = yield result
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/scheduler.py", line 2184, in gather
    who_has, rpc=self.rpc, close=False, serializers=serializers)
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/utils_comm.py", line 66, in gather_from_workers
    r = yield c
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/worker.py", line 2794, in get_data_from_worker
    max_connections=max_connections)
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/core.py", line 448, in send_recv
    raise Exception(response['text'])
Exception: get_data() got an unexpected keyword argument 'max_connections'
```

@mrocklin - have you seen this before? I'm working off a clean install as of an hour ago so this is pointing to dask/distributed master.

**Comment by guillaumeeb** [comment]
@jahmman, have you find a solution to this?

**Comment by jhamman** [comment]
I think we can close this now. I haven't seen it in a while so I'm guessing it was an environment issue.
